# Generated by Django 3.2.25 on 2024-07-28 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_review_unique_review'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_review',
        ),
    ]
